### ISSUE TITLE
Cannot import module under Python 3

### ISSUE THREAD

**Issue by TimothyADavis** [vrodgom/statmorph#3]
Under python 3.5.4 I cannot import the statmorph module. I get the following error:

```
Traceback (most recent call last):
  File "tryCAS.py", line 8, in <module>
    import statmorph
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/statmorph/__init__.py", line 1, in <module>
    from .statmorph import SourceMorphology, source_morphology
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/statmorph/statmorph.py", line 15, in <module>
    import skimage.measure
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/skimage/util/__init__.py", line 5, in <module>
    from .apply_parallel import apply_parallel
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/dask/array/__init__.py", line 46, in <module>
    from . import random, linalg, ghost, learn, fft
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/dask/array/ghost.py", line 8, in <module>
    from toolz.curried import map
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/toolz/curried/__init__.py", line 53, in <module>
    _curry_namespace(vars(toolz)),
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/toolz/curried/__init__.py", line 48, in _curry_namespace
    for name, f in ns.items() if '__' not in name
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/toolz/curried/__init__.py", line 48, in <genexpr>
    for name, f in ns.items() if '__' not in name
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/toolz/curried/__init__.py", line 42, in _should_curry
    return (callable(f) and _nargs(f) > 1 or f in do_curry)
  File "/Users/tdavis/anaconda/lib/python3.5/site-packages/toolz/curried/__init__.py", line 35, in _nargs
    return len(inspect.getargspec(f).args)
  File "/Users/tdavis/anaconda/lib/python3.5/inspect.py", line 1050, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

It seems to work ok on old Python 2.7 (assuming I remove the print brackets from the example, which seems to be in Python 3...)

Many thanks!

**Comment by vrodgom** [comment]
Sorry, I cannot reproduce this error. It works fine for me on Python 3.5.4. I suspect it might be an issue with skimage. Have you tried doing "conda update --all"?

**Comment by TimothyADavis** [comment]
...that seems to have fixed the issue, apologies for bothering you! Python updates/changes things a lot more than the other languages I am used to.
